"""change facility 

Revision ID: 5a6e7fb9c911
Revises: 2895c9581b2d
Create Date: 2024-01-01 20:59:23.264102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6e7fb9c911'
down_revision: Union[str, None] = '2895c9581b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Facilities', ['name'])
    op.create_unique_constraint(None, 'Facilities', ['geo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Facilities', type_='unique')
    op.drop_constraint(None, 'Facilities', type_='unique')
    # ### end Alembic commands ###
