"""user changes 

Revision ID: b99875fc0040
Revises: 5a6e7fb9c911
Create Date: 2024-01-01 23:13:03.960544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99875fc0040'
down_revision: Union[str, None] = '5a6e7fb9c911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_start_shift_notified')
    op.drop_column('Users', 'is_end_shift_notified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_end_shift_notified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('is_start_shift_notified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
