"""Test changes

Revision ID: f51cba5ac62d
Revises: 
Create Date: 2023-12-27 20:04:44.792499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51cba5ac62d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('facility_id', 'Shifts', type_='foreignkey')
    op.drop_constraint('facility_id', 'Users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('facility_id', 'Users', 'Facilities', ['current_facility_id'], ['id'])
    op.create_foreign_key('facility_id', 'Shifts', 'Facilities', ['facility_id'], ['id'])
    # ### end Alembic commands ###
